### ISSUE TITLE
gettext is broken when ablog is used

### ISSUE THREAD

**Issue by palkeo** [sunpy/ablog#30]
Hi,

When using "sphinx-build -b gettext . _build/locale" I have an error like that:

```
File "[...]/sphinx/builders/gettext.py", line 303, in finish
    message = message.replace('\\', r'\\'). \
AttributeError: 'NoneType' object has no attribute 'replace'
```
I added a debug statement in gettext.py, and it seems like the string being None is coming from:
`ablog/templates/catalog.html` line 16, which is:
`{{ post.date.strftime(gettext(ablog.post_date_format)) }}`

So it looks like ablog.post_date_format is None, for some reason? I tried specifying it explicitly in the conf.py for my sphinx, the problem didn't go away.

Thanks!

**Comment by nabobalis** [comment]
Do you have a small example I could run?

**Comment by nabobalis** [comment]
From my understanding, `post_date_format` is set in the config by default. 
So if it is coming from that statement, does it build run if you remove it from the html file?

**Comment by palkeo** [comment]
I removed all the gettext(ablog.post_date_format) from the templates and the build ran, yes.

And yes, it should be set by default, but if I specify it explicitly in the config, or not, it fails all the time.

**Comment by ViktorHaag** [comment]
This is a guess, but I wonder if it has to do with the string you might expect in `ablog.post_date_form` being something like `%d %B %Y`, that is, a string that can be used for formatting operations. Jinja2's documentation about the `gettext()` templating operation looks like it might be sensitive to strings with templatey items in them (http://jinja.pocoo.org/docs/2.10/extensions/#id2).

I'm unsure why the template would want to be "translating" a date format string like `%d %B %Y` before it passes it to `post.date.strftime`... what happens if you change the line in `catalog.html` to read `{{ post.date.strftime( ablog.post_date_format ) }}` instead?

**Comment by dgarcia360** [comment]
Same problem here. Do you know if gettext works with dynamic variables? I was thinking of making a pull-request removing the gettext from every template, let me know what do you think.

**Comment by nabobalis** [comment]
I tried to fix it a while ago but I got nowhere myself. Removing it seems the easier solution for now.

**Comment by nabobalis** [comment]
It has been removed from the templates via #38. I will do a release tonight or tomorrow.
